@startuml

scale 1

skinparam defaultFontName "D2Coding ligature"
skinparam defaultFontSize 11
skinparam shadowing false
skinparam classAttributeIconSize 0

skinparam linetype ortho
left to right direction

package org.apache.spark.ml {
    abstract class Transformer #Wheat {
        + {abstract} Dataset<Row> transform(Dataset<?> ratings)
        + {abstract} StructType transformSchema(StructType schema)
        + {abstract} Transformer copy(ParamMap extra)
        + {abstract} String uid()
    }
}

package com.r4tings.recommender.common.ml {

    package com.r4tings.recommender.common.ml.param {

        interface RatingCol{
            ~ Param<String> userCol()
            ~ Param<String> itemCol()
            ~ Param<String> ratingCol()
            ~ String getUserCol()
            ~ String getItemCol()
            ~ String getRatingCol()
            ~ RatingCol setUserCol(String value)
            ~ RatingCol setItemCol(String value)
            ~ RatingCol setRatingCol(String value)
        }

        interface Verbose{
            ~ BooleanParam verbose()
            ~ Boolean getVerbose()
            ~ Verbose setVerbose(Boolean value)
        }

        interface OutputCol{
            ~ Param<String> outputCol()
            ~ String getOutputCol()
            ~ OutputCol setOutputCol(String values)
        }

        interface GroupCol{
            ~ Param<Group> group()
            ~ Group getGroup()
            ~ String getGroupCol()
            ~ GroupCol setGroup(Group value)
            ~ GroupCol setGroupCol(String values)
        }
    }

    abstract class AbstractTransformer{
        + AbstractTransformer(String prefix)
        + StructType transformSchema(StructType schema)
        + Transformer copy(ParamMap extra)
        + String uid()
        + BooleanParam verbose()
        + Param<String> outputCol()
        + Param<String> userCol()
        + Param<String> itemCol()
        + Param<String> ratingCol()
        + Boolean getVerbose()
        + String getOutputCol()
        + String getUserCol()
        + String getItemCol()
        + String getRatingCol()
    }

    Verbose <|.. AbstractTransformer
    OutputCol <|.. AbstractTransformer
    RatingCol <|.. AbstractTransformer

}

    Transformer <|-left- AbstractTransformer

package com.r4tings.recommender.model.measures.similarity {

    abstract class RatingSimilarityMeasurer<T extends RatingSimilarityMeasurer<T>>{
        + RatingSimilarityMeasurer(String prefix)
        + Dataset<Row> transform(Dataset<?> ratings)
        + Param<Group> group()
        + BooleanParam imputeZero()
        + Param<Object[]> ids()
        + Group getGroup()
        + String getGroupCol()
        + Boolean getImputeZero()
        + Object[] getIds()
        + T setVerbose(Boolean value)
        + T setOutputCol(String value)
        + T setUserCol(String value)
        + T setItemCol(String value)
        + T setRatingCol(String value)
        + T setGroup(Group value)
        + T setGroupCol(String value)
        + T setImputeZero(Boolean value)
        + T setIds(Object... value)
        # {abstract} T self()
        # {abstract} Dataset<Row> execute(Dataset<Row> ratingDS)
        # Dataset<Row> compute(Dataset<Row> ratingDS, UserDefinedFunction similarityMeasure)
    }

    class PearsonSimilarityMeasurer{
        + PearsonSimilarityMeasurer(String prefix)
        # PearsonSimilarityMeasurer self()
        # Dataset<Row> execute(Dataset<Row> ratingDS)
    }


    enum SimilarityMeasure {
        COSINE
        PEARSON
        MANHATTAN
        WEIGHTED_MANHATTAN
        EUCLIDEAN
        WEIGHTED_EUCLIDEAN
        BINARY_SMC
        BINARY_JACCARD
        BINARY_EXTENDED_JACCARD
        + SimilarityMeasure(String description)
        + {abstract} UserDefinedFunction invoke(Boolean imputeZero, Boolean verbose)
    }

    AbstractTransformer <|-- RatingSimilarityMeasurer
    GroupCol <|.. RatingSimilarityMeasurer
    RatingSimilarityMeasurer <|-left- PearsonSimilarityMeasurer
    SimilarityMeasure <.right. PearsonSimilarityMeasurer


}

com.r4tings.recommender.common.ml.param -[hidden]- com.r4tings.recommender.model.measures.similarity

@enduml